server {
  listen 80;
  client_max_body_size 12m;
  root /usr/share/nginx/html;
  location /api/ {
    proxy_pass http://backend:5000;
    proxy_read_timeout 120s;
    proxy_set_header Host $host;
  }
  location / {
    try_files $uri /index.html;
  }
}
