"""device transport

Revision ID: 033f7aecb24c
Revises: f7e190a83a3e
Create Date: 2026-09-27 09:52:45.397977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '033f7aecb24c'
down_revision = 'f7e190a83a3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_column('transport')

    # ### end Alembic commands ###
