"""scans plots review labels disease profiles

Revision ID: 162ce3b9c441
Revises: 
Create Date: 2026-09-26 12:54:09.823571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '162ce3b9c441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=20), nullable=False),
    sa.Column('disease', sa.String(length=64), nullable=False),
    sa.Column('name_en', sa.String(length=80), nullable=False),
    sa.Column('name_ms', sa.String(length=80), nullable=False),
    sa.Column('spread_mode', sa.String(length=16), nullable=False),
    sa.Column('weather_model', sa.String(length=16), nullable=False),
    sa.Column('temp_min', sa.Float(), nullable=True),
    sa.Column('temp_max', sa.Float(), nullable=True),
    sa.Column('moisture', sa.JSON(), nullable=True),
    sa.Column('advice_type', sa.String(length=24), nullable=False),
    sa.Column('spread_radius_km', sa.Float(), nullable=False),
    sa.Column('report_decay_days', sa.Float(), nullable=False),
    sa.Column('source_refs', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop', 'disease', name='uq_profile_crop_disease')
    )
    op.create_table('plots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('crop', sa.String(length=20), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('grid_cell', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('area_m2', sa.Float(), nullable=True),
    sa.Column('num_plants', sa.Integer(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_plots_grid_cell'), ['grid_cell'], unique=False)
        batch_op.create_index(batch_op.f('ix_plots_region'), ['region'], unique=False)

    op.create_table('scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=True),
    sa.Column('crop', sa.String(length=20), nullable=False),
    sa.Column('diagnosis', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('top3', sa.JSON(), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lon', sa.Float(), nullable=False),
    sa.Column('grid_cell', sa.String(length=32), nullable=False),
    sa.Column('region', sa.String(length=8), nullable=False),
    sa.Column('image_path', sa.String(length=255), nullable=True),
    sa.Column('heatmap_path', sa.String(length=255), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('is_stub', sa.Boolean(), nullable=False),
    sa.Column('review_status', sa.String(length=16), nullable=False),
    sa.Column('confirmed_label', sa.String(length=64), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_crop'), ['crop'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_diagnosis'), ['diagnosis'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_grid_cell'), ['grid_cell'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_is_simulated'), ['is_simulated'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_plot_id'), ['plot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_region'), ['region'], unique=False)
        batch_op.create_index(batch_op.f('ix_scans_review_status'), ['review_status'], unique=False)

    op.create_table('confirmed_labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=20), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('model_label', sa.String(length=64), nullable=False),
    sa.Column('reviewer', sa.String(length=80), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['scan_id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('confirmed_labels')
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scans_review_status'))
        batch_op.drop_index(batch_op.f('ix_scans_region'))
        batch_op.drop_index(batch_op.f('ix_scans_plot_id'))
        batch_op.drop_index(batch_op.f('ix_scans_is_simulated'))
        batch_op.drop_index(batch_op.f('ix_scans_grid_cell'))
        batch_op.drop_index(batch_op.f('ix_scans_diagnosis'))
        batch_op.drop_index(batch_op.f('ix_scans_crop'))
        batch_op.drop_index(batch_op.f('ix_scans_created_at'))

    op.drop_table('scans')
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_plots_region'))
        batch_op.drop_index(batch_op.f('ix_plots_grid_cell'))

    op.drop_table('plots')
    op.drop_table('disease_profiles')
    # ### end Alembic commands ###
