"""device commands and schedules

Revision ID: 54c02d065c54
Revises: 033f7aecb24c
Create Date: 2026-09-27 10:02:00.585913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54c02d065c54'
down_revision = '033f7aecb24c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('control_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('time_local', sa.String(length=5), nullable=False),
    sa.Column('days', sa.String(length=7), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_run_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('control_schedules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_control_schedules_plot_id'), ['plot_id'], unique=False)

    op.create_table('device_commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.String(length=40), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('checks', sa.JSON(), nullable=True),
    sa.Column('transport', sa.String(length=16), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('requested_by', sa.Integer(), nullable=True),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['schedule_id'], ['control_schedules.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_commands_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_plot_id'), ['plot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_commands_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('device_commands', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_commands_status'))
        batch_op.drop_index(batch_op.f('ix_device_commands_plot_id'))
        batch_op.drop_index(batch_op.f('ix_device_commands_device_id'))

    op.drop_table('device_commands')
    with op.batch_alter_table('control_schedules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_control_schedules_plot_id'))

    op.drop_table('control_schedules')
    # ### end Alembic commands ###
