"""harvest records

Revision ID: 8559840400b4
Revises: 54c02d065c54
Create Date: 2026-09-27 10:20:06.564745

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8559840400b4'
down_revision = '54c02d065c54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harvest_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('harvested_on', sa.Date(), nullable=False),
    sa.Column('kg', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(length=200), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('harvest_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_harvest_records_plot_id'), ['plot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('harvest_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_harvest_records_plot_id'))

    op.drop_table('harvest_records')
    # ### end Alembic commands ###
