"""devices and sensor readings

Revision ID: bce9ed9af513
Revises: 3acf5afcff75
Create Date: 2026-09-27 06:34:06.187601

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'bce9ed9af513'
down_revision = '3acf5afcff75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uid', sa.String(length=64), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('key_hash', sa.String(length=255), nullable=False),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('sim_state', sa.JSON(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uid')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_plot_id'), ['plot_id'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(), nullable=False),
    sa.Column('soil_moisture_pct', sa.Float(), nullable=True),
    sa.Column('soil_temp_c', sa.Float(), nullable=True),
    sa.Column('air_temp_c', sa.Float(), nullable=True),
    sa.Column('air_rh_pct', sa.Float(), nullable=True),
    sa.Column('soil_ec_ds_m', sa.Float(), nullable=True),
    sa.Column('light_lux', sa.Float(), nullable=True),
    sa.Column('battery_pct', sa.Float(), nullable=True),
    sa.Column('leaf_wet', sa.Boolean(), nullable=True),
    sa.Column('is_simulated', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['device_id'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['plot_id'], ['plots.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensor_readings_device_id'), ['device_id'], unique=False)
        batch_op.create_index('ix_sensor_readings_plot_ts', ['plot_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.drop_index('ix_sensor_readings_plot_ts')
        batch_op.drop_index(batch_op.f('ix_sensor_readings_device_id'))

    op.drop_table('sensor_readings')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_plot_id'))

    op.drop_table('devices')
    # ### end Alembic commands ###
