"""fertiliser products and crop requirements

Revision ID: d3941a4c9c8f
Revises: 162ce3b9c441
Create Date: 2026-09-26 13:03:13.219832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3941a4c9c8f'
down_revision = '162ce3b9c441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crop_requirements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crop', sa.String(length=20), nullable=False),
    sa.Column('stage', sa.String(length=20), nullable=False),
    sa.Column('n', sa.Float(), nullable=False),
    sa.Column('p2o5', sa.Float(), nullable=False),
    sa.Column('k2o', sa.Float(), nullable=False),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('crop', 'stage', name='uq_requirement_crop_stage')
    )
    op.create_table('fertiliser_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('n', sa.Float(), nullable=False),
    sa.Column('p2o5', sa.Float(), nullable=False),
    sa.Column('k2o', sa.Float(), nullable=False),
    sa.Column('mgo', sa.Float(), nullable=False),
    sa.Column('price_rm_per_kg', sa.Float(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fertiliser_products')
    op.drop_table('crop_requirements')
    # ### end Alembic commands ###
