"""plot owner and scan user

Revision ID: f7e190a83a3e
Revises: bce9ed9af513
Create Date: 2026-09-27 09:48:56.208529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7e190a83a3e'
down_revision = 'bce9ed9af513'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_plots_owner_id'), ['owner_id'], unique=False)
        batch_op.create_foreign_key('fk_plots_owner_id_users', 'users', ['owner_id'], ['id'])

    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_scans_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_scans_user_id_users', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('scans', schema=None) as batch_op:
        batch_op.drop_constraint('fk_scans_user_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_scans_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('plots', schema=None) as batch_op:
        batch_op.drop_constraint('fk_plots_owner_id_users', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_plots_owner_id'))
        batch_op.drop_column('owner_id')

    # ### end Alembic commands ###
